Repository WildCodeSchool/lyon-js-sept2020-p3-oufgarden-back-office, pull requests merged in 2021-01, with the labels that each got.

#19 Article
  package-lock.json
  package.json
  public/index.html
  src/components/Adherents.js
  src/components/App.js
  src/components/ArticleCreation.js
  src/components/Articles.js
  src/components/ListArticles.js
  src/components/Login.js
  src/components/TextEditor.js
  src/components/style/ArticleCreation.scss
  src/components/style/Articles.scss
  src/components/style/ListArticles.scss
  src/components/style/TextEditor.scss
Labels: Ready for prod

#26 Tag creation page
  src/components/App.js
  src/components/TagsPage.js
  src/components/style/TagsPage.scss
Labels: Ready for prod

#30 Css form
  src/components/Adherents.js
  src/components/App.js
  src/components/GardenCreation.js
  src/components/MemberCreation.js
  src/components/MemberEdition.js
  src/components/style/MemberCreation.scss
Labels: Ready for prod

#28 Logout
  src/components/Login.js
  src/components/MemberCreation.js
  src/components/MemberEdition.js
  src/components/Navbar.js
  src/components/style/Navbar.scss
Labels: Ready for prod

#31 Article creation fetching
  package.json
  public/index.html
  src/components/ArticleCreation.js
  src/components/GardenCreation.js
  src/components/ListArticles.js
  src/components/TextEditor.js
  src/components/style/ArticleCreation.scss
  src/components/style/TagsPage.scss
  src/components/style/TextEditor.scss
Labels: Ready for prod

#39 Delete modal
  package-lock.json
  package.json
  src/components/Adherents.js
  src/components/ArticleCreation.js
  src/components/ArticleList.js
  src/components/Garden.js
  src/components/GardenCreation.js
  src/components/TagsPage.js
  src/components/TextEditor.js
  src/components/style/ArticleCreation.scss
  src/components/style/TextEditor.scss
Labels: Ready for prod

#37 Improving garden pages back office
  src/components/ArticleList.js
  src/components/GardenCreation.js
Labels: Ready for prod

#38 User creation adding fields
  package-lock.json
  src/components/Adherents.js
  src/components/App.js
  src/components/ArticleList.js
  src/components/Login.js
  src/components/MemberCreation.js
  src/components/MemberDetail.js
  src/components/MemberEdition.js
  src/components/TextEditor.js
  src/components/style/AdherentList.scss
  src/components/style/MemberDetail.scss
  src/services/API.js
Labels: Ready for prod

#41 Login css
  src/components/Login.js
  src/components/style/Login.scss
Labels: Ready for Validation

#51 Improving back office details
  package-lock.json
  package.json
  src/components/Adherents.js
  src/components/App.js
  src/components/ArticleCreation.js
  src/components/ArticleDetail.js
  src/components/ArticleList.js
  src/components/AvatarEdition.js
  src/components/ButtonListCreation.js
  src/components/Calendar.js
  src/components/Comment.js
  src/components/CommentList.js
  src/components/Garden.js
  src/components/GardenCreation.js
  src/components/GardenDetail.js
  src/components/Login.js
  src/components/MemberCreation.js
  src/components/MemberDetail.js
  src/components/MemberEdition.js
  src/components/Navbar.js
  src/components/TagsPage.js
  src/components/ZoneEdition.js
  src/components/style/AdherentList.scss
  src/components/style/ArticleDetail.scss
  src/components/style/ButtonListCreation.scss
  src/components/style/Calendar.scss
  src/components/style/Comment.scss
  src/components/style/CommentList.scss
  src/components/style/Garden.scss
  src/components/style/GardenCreation.scss
  src/components/style/GardenDetail.scss
  src/components/style/ListArticles.scss
  src/components/style/Login.scss
  src/components/style/MemberCreation.scss
  src/components/style/Navbar.scss
  src/components/style/TagsPage.scss
  src/images/Fichier 2.png
  src/images/Fichier 3.png
  src/images/jardin-active.png
  src/images/jardin.png
Labels: Ready for Validation

#42 Email user creation
  package-lock.json
  src/components/Adherents.js
  src/components/ArticleList.js
  src/components/AvatarEdition.js
  src/components/MemberCreation.js
  src/components/MemberDetail.js
  src/components/MemberEdition.js
  src/components/style/AdherentList.scss
  src/components/style/ListArticles.scss
  src/components/style/MemberCreation.scss
Labels: Ready for Validation

#52 started working on the filter, still have to change it for when there…
  src/components/Adherents.js
  src/components/ArticleList.js
  src/components/AvatarEdition.js
  src/components/MemberDetail.js
  src/components/MemberEdition.js
  src/components/style/AdherentList.scss
  src/components/style/ListArticles.scss
  src/components/style/MemberCreation.scss
Labels: WIP

#53 first working version of the agenda, with our own email address for now
  src/components/App.js
  src/components/PublicCalendar.js
  src/components/style/PublicCalendar.scss
Labels: Ready for prod
